/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.diego.spectrosplit;

import java.util.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
     private File arquivoSelecionado;
     private File pastaSelecionada;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSelecionar = new javax.swing.JButton();
        campoArquivo = new javax.swing.JTextField();
        btnProcessar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        campoDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spectro Split");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnSelecionar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnSelecionar.setText("Selecionar CSV");
        btnSelecionar.addActionListener(this::btnSelecionarActionPerformed);

        campoArquivo.setEditable(false);
        campoArquivo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        btnProcessar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(this::btnProcessarActionPerformed);

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Spectro Split");

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton2.setText("Selecionar Destino");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        campoDestino.setEditable(false);
        campoDestino.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel2.setText("Autor: Diego Wobeto Maglia Muller");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(292, 292, 292))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcessar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoArquivo)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        JFileChooser chooser = new JFileChooser();

        // 🔹 filtro para CSV
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Files", "csv"));

        int resultado = chooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivo = chooser.getSelectedFile();

            // salva referência
            arquivoSelecionado = arquivo;

            // mostra na tela (nome ou caminho)
            campoArquivo.setText(arquivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    public void processarCSV(File arquivo, File pastaBase) {
        try {
        BufferedReader br = new BufferedReader(new FileReader(arquivo));

        // 🔹 1. Ler cabeçalhos
        String linha1 = br.readLine();
        String linha2 = br.readLine();

        String[] nomes = linha1.split(",");
        String[] tipos = linha2.split(",");

        // 🔹 2. Mapear grupos
        Map<String, List<Integer>> grupos = new HashMap<>();

        for (int i = 0; i < tipos.length; i++) {
            if (tipos[i].trim().equalsIgnoreCase("Abs")) {

                // nome base está na coluna anterior
                String nomeBase = nomes[i - 1].trim();

                grupos.putIfAbsent(nomeBase, new ArrayList<>());
                grupos.get(nomeBase).add(i);
            }
        }

        // 🔹 3. Criar pasta Spectro Split
        File pastaSaida = new File(pastaBase, "Spectro Split");

        if (!pastaSaida.exists()) {
            pastaSaida.mkdirs();
        }

        // 🔹 4. Preparar writers (um por grupo)
        Map<String, BufferedWriter> writers = new HashMap<>();

        for (String nome : grupos.keySet()) {

            String nomeArquivo = nome.replace(" ", "_") + ".csv";
            File arquivoSaida = new File(pastaSaida, nomeArquivo);

            BufferedWriter bw = new BufferedWriter(new FileWriter(arquivoSaida));

            // cabeçalho
            List<Integer> indices = grupos.get(nome);
            for (int i = 0; i < indices.size(); i++) {
                bw.write("Abs_" + (i + 1));
                if (i < indices.size() - 1) bw.write(",");
            }
            bw.newLine();

            writers.put(nome, bw);
        }

        // 🔹 5. Processar linhas (streaming → melhor performance)
        String linha;

        while ((linha = br.readLine()) != null) {

            String[] valores = linha.split(",");

            for (String nome : grupos.keySet()) {

                List<Integer> indices = grupos.get(nome);
                BufferedWriter bw = writers.get(nome);

                for (int i = 0; i < indices.size(); i++) {
                    int index = indices.get(i);

                    if (index < valores.length) {
                        bw.write(valores[index]);
                    }

                    if (i < indices.size() - 1) bw.write(",");
                }

                bw.newLine();
            }
        }

        // 🔹 6. Fechar tudo
        br.close();

        for (BufferedWriter bw : writers.values()) {
            bw.close();
        }

        JOptionPane.showMessageDialog(this,
                "Processamento concluído!\nArquivos salvos em:\n" + pastaSaida.getAbsolutePath());

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao processar CSV: " + e.getMessage());
    }
    }
    
    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
            if (arquivoSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Selecione o arquivo CSV!");
        return;
    }

    if (pastaSelecionada == null) {
        JOptionPane.showMessageDialog(this, "Selecione a pasta de destino!");
        return;
    }

    System.out.println("Processando arquivo: " + arquivoSelecionado.getAbsolutePath());

    processarCSV(arquivoSelecionado, pastaSelecionada);
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();

    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);

    int resultado = chooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        pastaSelecionada = chooser.getSelectedFile();

        campoDestino.setText(pastaSelecionada.getAbsolutePath());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JTextField campoArquivo;
    private javax.swing.JTextField campoDestino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
