name: Build SpectroSplit EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package

      - name: Create EXE with jpackage
        run: jpackage --input target --name SpectroSplit --main-jar SpectroSplit-1.0-SNAPSHOT.jar --main-class com.diego.spectrosplit.MainFrame --type exe --win-shortcut --win-menu

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SpectroSplit-EXE
          path: "*.exe"